<a href="https://colab.research.google.com/github/Rahulgarg95/jovian_pandas/blob/master/numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1SJHBYJ_g9FPuCUQX-8lqQlFgc6Yj3KRd')

     |████████████████████████████████| 71kB 1.6MB/s 


> ### **Assignment 2 - Numpy Array Operations** 

In [2]:
!pip install jovian --upgrade -q

In [3]:
import jovian

In [66]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/rahulgarg95/numpy-array-operations


'https://jovian.ml/rahulgarg95/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [64]:
# List of functions explained 
function1 = np.transpose
function2 = np.arange
function3 = np.matmul
function4 = np.add
function5 = np.reshape

## Function 1 - np.transpose

The above function simply converts row to columns and vice versa. It has no effect on 1-D arrays.

In [7]:
# Example 1 - working
arr1 = np.arange(4).reshape(2,2)
print(arr1)

print('Shape Before Transpose', arr1.shape)

trans_arr=np.transpose(arr1)
print('\nTransposed Array\n')
print(trans_arr)
print('Shape After Transpose', trans_arr.shape)

[[0 1]
 [2 3]]
Shape Before Transpose (2, 2)

Transposed Array

[[0 2]
 [1 3]]
Shape After Transpose (2, 2)


So in the above we have a 2*2 matrix. Once the transpose function is applied first row [1,2] becomes first column and vice versa. The same is observed for second row and column.

In [8]:
# Example 2 - working
arr2=np.array([1,2,3,4,5,6])

print(arr2.shape)

trans_arr=np.transpose(arr2)

print(trans_arr)

print(trans_arr.shape)

(6,)
[1 2 3 4 5 6]
(6,)


The above example illustrates transpose effect on 1-D arrays. The shape remains same which seems logical.

In [9]:
# Example 3 - working
arr1 = np.arange(6).reshape(3,2)
print(arr1)

print('Shape Before Transpose', arr1.shape)

trans_arr=np.transpose(arr1)
print('\nTransposed Array\n')
print(trans_arr)
print('Shape After Transpose', trans_arr.shape)

print(arr1.T)

[[0 1]
 [2 3]
 [4 5]]
Shape Before Transpose (3, 2)

Transposed Array

[[0 2 4]
 [1 3 5]]
Shape After Transpose (2, 3)
[[0 2 4]
 [1 3 5]]


The above example clearly illustrates transpose function reverses the shape of matrix. We have also demonstrated now to transpose a matrix using .T

The main need of transposing a matrix comes when multiplying multiple arrays and their dimension do not align, will explain in detail with function 3.

In [10]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/rahulgarg95/numpy-array-operations


'https://jovian.ml/rahulgarg95/numpy-array-operations'

## Function 2 - np.arange

Returns an array with evenly spaced elements as per interval.

In [11]:
# Example 1 - working
arr1=np.arange(4,10)

print(arr1)

print(arr1.shape)

[4 5 6 7 8 9]
(6,)


The above example illustrates classic use of numpy arange function which prints elements in a list in the specified range.The first argument is start counter(implicit) and second arg is end counter(explicit).

In [12]:
# Example 2 - working
arr2=np.arange(start=1,stop=54,step=5)

print(arr2)

print('Array Length => ',len(arr2))
print('Array Shape => ',arr2.shape)

[ 1  6 11 16 21 26 31 36 41 46 51]
Array Length =>  11
Array Shape =>  (11,)


The above example takes example 1 a little further with use of step argument.The step argument tells the function to print the next element by adding start val with step value.

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
arr3=np.arange(10,10.7,0.1)

print(arr3.tolist())

[10.0, 10.1, 10.2, 10.299999999999999, 10.399999999999999, 10.499999999999998, 10.599999999999998]


np.arange function might give inconsistent results with floating point numbers better to use linespace in such scenarios.

The above functions is used when you want a sequence of numbers.

In [14]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/rahulgarg95/numpy-array-operations


'https://jovian.ml/rahulgarg95/numpy-array-operations'

## Function 3 - np.matmul

It returns multiplication of two matrix.

In [15]:
# Example 1 - working
arr1=np.arange(1,10).reshape(3,3)
print('Array 1: \n',arr1)

arr2=np.arange(5,50,5).reshape(3,3)
print('\nArray 2: \n',arr2)

arr3=np.matmul(arr1,arr2)
print('\nResult Matrix: \n', arr3)

Array 1: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2: 
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Result Matrix: 
 [[150 180 210]
 [330 405 480]
 [510 630 750]]


The above example illustrates matrix multiplication of (3x3) matrix.
The first row is multiplied with first column and the sum of the same is put at index(0,0) and similiarly for other elements.

In [16]:
# Example 2 - working
arr1=np.arange(1,7).reshape(3,2)
print('Array 1: \n',arr1)

arr2=np.arange(1,13,2).reshape(2,3)
print('\nArray 2: \n',arr2)

print('\nResultant Array:')
print(np.matmul(arr1,arr2))

Array 1: 
 [[1 2]
 [3 4]
 [5 6]]

Array 2: 
 [[ 1  3  5]
 [ 7  9 11]]

Resultant Array:
[[15 21 27]
 [31 45 59]
 [47 69 91]]


The above example shows multiplication of two arrays of different shapes.

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
arr1=np.arange(1,7).reshape(3,2)
print('Array 1: \n',arr1)

arr2=np.arange(1,13,2).reshape(3,2)
print('\nArray 2: \n',arr2)

print('\nResultant Array:')
print(np.matmul(arr1,arr2))

Array 1: 
 [[1 2]
 [3 4]
 [5 6]]

Array 2: 
 [[ 1  3]
 [ 5  7]
 [ 9 11]]

Resultant Array:


ValueError: ignored

The above examples illustrates the vulnebility of matmul function.
Shape of arr1 = (3,2) Shape of arr2 = (3,2). For multiplication to happen arr1 column len should match arr2 row len (a,b) (c,d) => b==c. Hence we need to transpose the matrix(arr2) to get the desired output.

The matmul functions is used deeply in neutral networks as multiple matrix are involved as hidden layers.

In [18]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/rahulgarg95/numpy-array-operations


'https://jovian.ml/rahulgarg95/numpy-array-operations'

## Function 4 - np.add

The above function is used when we want two compute the addition of two matrix.

In [25]:
# Example 1 - working
arr1=np.arange(1,10).reshape(3,3)
print('Array 1: \n',arr1)

arr2=np.arange(4,46,5).reshape(3,3)
print('\nArray 2: \n', arr2)

result_arr=np.add(arr1,arr2)
print('\nResultant Array: \n', result_arr)

Array 1: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2: 
 [[ 4  9 14]
 [19 24 29]
 [34 39 44]]

Resultant Array: 
 [[ 5 11 17]
 [23 29 35]
 [41 47 53]]


The above example illustrates the classic addition of two matrix have same shape.The element of arr1[i][j] is added to corresponding el of arr2[i][j], for same values of i & j.

In [29]:
# Example 2 - working
arr1=np.arange(1,10).reshape(3,3)
print('Array 1: \n',arr1)

arr2=np.arange(5,16,5).reshape(1,3)
print('\nArray 2: \n', arr2)

result_arr=np.add(arr1,arr2)
print('\nResultant Array: \n', result_arr)

Array 1: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2: 
 [[ 5 10 15]]

Resultant Array: 
 [[ 6 12 18]
 [ 9 15 21]
 [12 18 24]]


The above example illustrates use of broadcasting principle used in np.add function.Here arr2 is of size (1,3) and arr1 is of size (3,3) so to make arr2 of size (3,3) first row is repeated three times to create (3,3) matrix and then addition happens.

In [53]:
# Example 3 - breaking (to illustrate when it breaks)
arr1=np.arange(1,7).reshape(3,2)
#arr1=np.array([10,20,30]).reshape(3,1)
print('Array 1: \n',arr1)

#arr2=np.arange(5,61,5).reshape(3)
arr2=np.array([1,2,3])
#arr2 = arr2[:, np.newaxis]
print('\nArray 2: \n', arr2)

result_arr=np.add(arr2,arr1)
print('\nResultant Array: \n', result_arr)

Array 1: 
 [[1 2]
 [3 4]
 [5 6]]

Array 2: 
 [1 2 3]


ValueError: ignored

The above example 3 illustrates where broadcasting does not work. As arr 2 is a vector hence it cannot to broadcasted accordingly. Hence we need to add new axis the code is commented. Once axis is added the new shape of arr2 is (3,1) which can be easily broadcasted and np.add works fine then.

The matrix addition is quite useful while addition of bais to existing matrix in neutral network.

In [54]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/rahulgarg95/numpy-array-operations


'https://jovian.ml/rahulgarg95/numpy-array-operations'

## Function 5 - np.reshape

np,.reshape is quite useful to get a matrix with exact deminesions required when a bunch of numbers are present in an 1-D array or list to perform a set of operations.

In [55]:
# Example 1 - working
arr1=np.arange(1,7).reshape(3,2)

The above example gives a basic reshape example of conveting a 1-D vector to 3x2 matrix.

In [61]:
# Example 2 - working
a=np.array([[1,2,3],[4,5,6]])
print(a.shape,'\n',a)

b = a.ravel()
print('\nFlattened Array: ')
print(b)

b = b.reshape((2, 3))
print('Reshaped array: \n',b)

(2, 3) 
 [[1 2 3]
 [4 5 6]]

Flattened Array: 
[1 2 3 4 5 6]
Reshaped array: 
 [[1 2 3]
 [4 5 6]]


Example 2 illustrates that reshape is basically an inverse operation to array flattening.

In [62]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.zeros((3, 2))
b = a.T.reshape(3*2)
b[0] = 50
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


The above example shows a corner case of reshape where it demonstrates during reshape a seperated copy is created in some cases where other operations may not effect the initial array as desired in the above example.

One of the most used fucntionality while performing operations between multiple matrix.

In [63]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/rahulgarg95/numpy-array-operations


'https://jovian.ml/rahulgarg95/numpy-array-operations'

## Conclusion

We have demonstrated 5 common functions used using matrix operations. Numpy array operations provides faster computing than python lists and other functions like mean,median,max,min are used in data analysis. Funtions like add, matmul find more use in deep learning and neural networks and the whole numpy module becomes a ground for further pandas understanding and operations.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Tutorial Point : https://www.tutorialspoint.com/numpy/index.htm

In [67]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/rahulgarg95/numpy-array-operations


'https://jovian.ml/rahulgarg95/numpy-array-operations'